"""NUCC Health Care Provider Taxonomy descriptions for autocomplete."""

TAXONOMY_DESCRIPTIONS: list[str] = [
    "Acupuncturist",
    "Acute Care Clinical Nurse Specialist",
    "Acute Care Nurse Practitioner",
    "Addiction (Substance Use Disorder) Counselor",
    "Addiction (Substance Use Disorder) Psychologist",
    "Addiction (Substance Use Disorder) Registered Nurse",
    "Addiction Medicine (Anesthesiology) Physician",
    "Addiction Medicine (Family Medicine) Physician",
    "Addiction Medicine (Internal Medicine) Physician",
    "Addiction Medicine (Preventive Medicine) Physician",
    "Addiction Medicine (Psychiatry & Neurology) Physician",
    "Addiction Psychiatry Physician",
    "Administrator Registered Nurse",
    "Adolescent Medicine (Family Medicine) Physician",
    "Adolescent Medicine (Internal Medicine) Physician",
    "Adolescent and Children Mental Health Clinic/Center",
    "Adult Care Home Facility",
    "Adult Companion",
    "Adult Congenital Heart Disease Physician",
    "Adult Day Care Clinic/Center",
    "Adult Development & Aging Psychologist",
    "Adult Health Clinical Nurse Specialist",
    "Adult Health Nurse Practitioner",
    "Adult Medicine Physician",
    "Adult Mental Health Clinic/Center",
    "Adult Psychiatric/Mental Health Clinical Nurse Specialist",
    "Adult Psychiatric/Mental Health Registered Nurse",
    "Adult Reconstructive Orthopaedic Surgery Physician",
    "Advanced Heart Failure and Transplant Cardiology Physician",
    "Advanced Practice Dental Therapist",
    "Advanced Practice Midwife",
    "Aerospace Medicine Physician",
    "Air Ambulance",
    "Air Carrier",
    "Allergy & Immunology (Internal Medicine) Physician",
    "Allergy & Immunology Physician",
    "Allergy Physician",
    "Alzheimer Center (Dementia Center)",
    "Ambulance",
    "Ambulatory Care Pharmacist",
    "Ambulatory Care Registered Nurse",
    "Ambulatory Family Planning Facility",
    "Ambulatory Fertility Facility",
    "Ambulatory Surgical Clinic/Center",
    "Ambulatory Women's Health Care Registered Nurse",
    "Amputee Clinic/Center",
    "Anaplastologist",
    "Anatomic Pathology & Clinical Pathology Physician",
    "Anatomic Pathology Physician",
    "Anesthesiologist Assistant",
    "Anesthesiology Physician",
    "Art Therapist",
    "Assistant Behavior Analyst",
    "Assistant Health Information Record Technician",
    "Assisted Living Facility",
    "Assisted Living Facility (Behavioral Disturbances)",
    "Assisted Living Facility (Mental Illness)",
    "Assistive Technology Practitioner Audiologist",
    "Assistive Technology Practitioner Rehabilitation Counselor",
    "Assistive Technology Supplier Audiologist",
    "Assistive Technology Supplier Rehabilitation Counselor",
    "Athletic Trainer",
    "Attendant Care Provider",
    "Audiologist",
    "Audiologist-Hearing Aid Fitter",
    "Audiology Assistant",
    "Augmentative Communication Clinic/Center",
    "Basic Emergency Medical Technician",
    "Behavior Analyst",
    "Behavior Technician",
    "Behavioral Neurology & Neuropsychiatry Physician",
    "Biochemist",
    "Biomedical Engineer",
    "Biomedical Engineering Technician",
    "Biomedical Photographer",
    "Biostatiscian",
    "Birthing Clinic/Center",
    "Blind Rehabilitation Specialist/Technologist",
    "Blood Bank",
    "Blood Banking & Transfusion Medicine Physician",
    "Blood Banking Specialist/Technologist",
    "Body Imaging Physician",
    "Bone Densitometry Radiologic Technologist",
    "Brain Injury Medicine (Physical Medicine & Rehabilitation) Physician",
    "Brain Injury Medicine (Psychiatry & Neurology) Physician",
    "Bus",
    "Cardiac Rehabilitation Clinic/Center",
    "Cardiac Rehabilitation Registered Nurse",
    "Cardiac-Interventional Technology Radiologic Technologist",
    "Cardiology Pharmacist",
    "Cardiology Technician",
    "Cardiopulmonary Physical Therapist",
    "Cardiovascular Disease Physician",
    "Cardiovascular Invasive Specialist/Technologist",
    "Cardiovascular Specialist/Technologist",
    "Cardiovascular-Interventional Technology Radiologic Technologist",
    "Case Management Agency",
    "Case Management Registered Nurse",
    "Case Manager/Care Coordinator",
    "Certified Registered Nurse Anesthetist",
    "Certified Respiratory Therapist",
    "Chemical Pathology Physician",
    "Chemistry Pathology Specialist/Technologist",
    "Child & Adolescent Psychiatric/Mental Health Clinical Nurse Specialist",
    "Child & Adolescent Psychiatric/Mental Health Registered Nurse",
    "Child & Adolescent Psychiatry Physician",
    "Child & Family Psychiatric/Mental Health Clinical Nurse Specialist",
    "Child Abuse Pediatrics Physician",
    "Child Intellectual and/or Developmental Disabilities Respite Care",
    "Child Mental Illness Respite Care",
    "Child Physical Disabilities Respite Care",
    "Children's Chronic Disease Hospital",
    "Children's Hospital",
    "Children's Rehabilitation Hospital",
    "Children's Substance Abuse Rehabilitation Facility",
    "Chiropractor",
    "Chore Provider",
    "Chronic Care Clinical Nurse Specialist",
    "Chronic Disease Hospital",
    "Chronically Ill Psychiatric/Mental Health Clinical Nurse Specialist",
    "Clinic Pharmacy",
    "Clinic/Center",
    "Clinical & Laboratory Dermatological Immunology Physician",
    "Clinical & Laboratory Immunology (Allergy & Immunology) Physician",
    "Clinical & Laboratory Immunology (Internal Medicine) Physician",
    "Clinical Biochemical Genetics Physician",
    "Clinical Cardiac Electrophysiology Physician",
    "Clinical Child & Adolescent Psychologist",
    "Clinical Cytogenetics Physician",
    "Clinical Electrophysiology Physical Therapist",
    "Clinical Ethicist",
    "Clinical Exercise Physiologist",
    "Clinical Genetics (M.D.) Physician",
    "Clinical Informatics (Pathology) Physician",
    "Clinical Informatics Physician",
    "Clinical Laboratory Director (Non-physician)",
    "Clinical Medical Laboratory",
    "Clinical Molecular Genetics Physician",
    "Clinical Neurophysiology Physician",
    "Clinical Neuropsychologist",
    "Clinical Nurse Specialist",
    "Clinical Pathology Physician",
    "Clinical Pathology/Laboratory Medicine Physician",
    "Clinical Pharmacology Physician",
    "Clinical Psychologist",
    "Clinical Social Worker",
    "Cognitive & Behavioral Psychologist",
    "College Health Registered Nurse",
    "Colon & Rectal Surgery Physician",
    "Community Based Hospice Care Agency",
    "Community Health Clinic/Center",
    "Community Health Nurse Practitioner",
    "Community Health Registered Nurse",
    "Community Health Worker",
    "Community Health/Public Health Clinical Nurse Specialist",
    "Community Paramedic",
    "Community Psychiatric/Mental Health Clinical Nurse Specialist",
    "Community/Behavioral Health Agency",
    "Community/Retail Pharmacy",
    "Complex Family Planning Physician",
    "Compounded Sterile Preparations Pharmacist",
    "Compounding Pharmacy",
    "Comprehensive Outpatient Rehabilitation Facility (CORF)",
    "Computed Tomography Radiologic Technologist",
    "Contact Lens Fitter",
    "Contact Lens Technician/Technologist",
    "Continence Care Registered Nurse",
    "Continuing Education/Staff Development Registered Nurse",
    "Contractor",
    "Cornea and External Diseases Specialist Physician",
    "Corneal and Contact Management Optometrist",
    "Corporate Health Clinic/Center",
    "Counseling Psychologist",
    "Counselor",
    "Critical Access Hospital",
    "Critical Access Hospital Clinic/Center",
    "Critical Care Certified Respiratory Therapist",
    "Critical Care Medicine (Anesthesiology) Physician",
    "Critical Care Medicine (Internal Medicine) Physician",
    "Critical Care Medicine (Obstetrics & Gynecology) Physician",
    "Critical Care Medicine Clinical Nurse Specialist",
    "Critical Care Medicine Nurse Practitioner",
    "Critical Care Medicine Registered Nurse",
    "Critical Care Neonatal Nurse Practitioner",
    "Critical Care Pediatric Nurse Practitioner",
    "Critical Care Pharmacist",
    "Critical Care Registered Respiratory Therapist",
    "Custodial Care Facility",
    "Customized Equipment (DME)",
    "Cytopathology Physician",
    "Cytotechnology Specialist/Technologist",
    "Dance Therapist",
    "Darkroom Technician",
    "Day Training/Habilitation Specialist",
    "Deactivated - Christian Science Facility",
    "Deactivated - Christian Science Sanitorium",
    "Deactivated - Clinical Neuropsychologist",
    "Deactivated - Military Hospital",
    "Deactivated - Pharmacist",
    "Deactivated - Podiatrist",
    "Deactivated - Psychologist",
    "Deactivated - Psychologist Men & Masculinity",
    "Deactivated - Psychologist Psychotherapy",
    "Deactivated - Psychotherapy Women",
    "Dental Anesthesiology",
    "Dental Assistant",
    "Dental Clinic/Center",
    "Dental Hygienist",
    "Dental Laboratory",
    "Dental Laboratory Technician",
    "Dental Therapist",
    "Dentist",
    "Denturist",
    "Department of Veterans Affairs (VA) Pharmacy",
    "Dermatology Physician",
    "Dermatopathology (Pathology) Physician",
    "Dermatopathology Physician",
    "Developmental - Behavioral Pediatrics Physician",
    "Developmental Disabilities Clinic/Center",
    "Developmental Therapist",
    "Developmentally Disabled Services Day Training Agency",
    "Diabetes Educator Registered Nurse",
    "Diabetology (Family Medicine) Physician",
    "Diabetology (Internal Medicine) Physician",
    "Diagnostic Neuroimaging (Psychiatry & Neurology) Physician",
    "Diagnostic Neuroimaging (Radiology) Physician",
    "Diagnostic Radiology Physician",
    "Diagnostic Ultrasound Physician",
    "Dialysis Equipment & Supplies (DME)",
    "Dietary Manager",
    "Diplomate Laboratory Management Specialist/Technologist",
    "Doula",
    "Drama Therapist",
    "Driver",
    "Driving and Community Mobility Occupational Therapist",
    "Driving and Community Mobility Occupational Therapy Assistant",
    "Durable Medical Equipment & Medical Supplies",
    "EEG Specialist/Technologist",
    "EEG Technician",
    "Early Intervention Provider Agency",
    "Educational Certified Respiratory Therapist",
    "Educational Registered Respiratory Therapist",
    "Electrodiagnostic Medicine Physician",
    "Electroneurodiagnostic Specialist/Technologist",
    "Emergency Care Certified Respiratory Therapist",
    "Emergency Care Clinic/Center",
    "Emergency Care Registered Respiratory Therapist",
    "Emergency Clinical Nurse Specialist",
    "Emergency Medical Services (Emergency Medicine) Physician",
    "Emergency Medicine Pharmacist",
    "Emergency Medicine Physician",
    "Emergency Registered Nurse",
    "Emergency Response System Companies",
    "Emotionally Disturbed Childrens' Residential Treatment Facility",
    "End-Stage Renal Disease (ESRD) Treatment Clinic/Center",
    "Endocrinology, Diabetes & Metabolism Physician",
    "Endodontics",
    "Endoscopy Clinic/Center",
    "Enterostomal Therapy Registered Nurse",
    "Environmental Modification Occupational Therapist",
    "Environmental Modification Occupational Therapy Assistant",
    "Epilepsy Hospital Unit",
    "Epilepsy Physician",
    "Ergonomics Occupational Therapist",
    "Ergonomics Physical Therapist",
    "Ethics Clinical Nurse Specialist",
    "Exclusive Provider Organization",
    "Exercise & Sports Psychologist",
    "Eye Bank",
    "Eyewear Supplier",
    "Facial Plastic Surgery Physician",
    "Family Health Clinical Nurse Specialist",
    "Family Medicine Physician",
    "Family Nurse Practitioner",
    "Family Psychologist",
    "Federal Public Health Clinic/Center",
    "Federally Qualified Health Center (FQHC)",
    "Feeding, Eating & Swallowing Occupational Therapist",
    "Feeding, Eating & Swallowing Occupational Therapy Assistant",
    "Flight Registered Nurse",
    "Foot & Ankle Surgery Podiatrist",
    "Foot Surgery Podiatrist",
    "Forensic Pathology Physician",
    "Forensic Psychiatry Physician",
    "Forensic Psychologist",
    "Foster Care Agency",
    "Funeral Director",
    "Gastroenterology Physician",
    "Gastroenterology Registered Nurse",
    "General Acute Care Hospital",
    "General Care Certified Respiratory Therapist",
    "General Care Registered Respiratory Therapist",
    "General Practice Dentistry",
    "General Practice Physician",
    "General Practice Registered Nurse",
    "Genetic Counselor (M.S.)",
    "Genetics Clinic/Center",
    "Geriatric Care Certified Respiratory Therapist",
    "Geriatric Care Registered Respiratory Therapist",
    "Geriatric Medicine (Family Medicine) Physician",
    "Geriatric Medicine (Internal Medicine) Physician",
    "Geriatric Pharmacist",
    "Geriatric Physical Therapist",
    "Geriatric Psychiatry Physician",
    "Gerontological Nutrition Registered Dietitian",
    "Gerontology Clinical Nurse Specialist",
    "Gerontology Nurse Practitioner",
    "Gerontology Occupational Therapist",
    "Gerontology Registered Nurse",
    "Geropsychiatric Psychiatric/Mental Health Clinical Nurse Specialist",
    "Glaucoma Specialist (Ophthalmology) Physician",
    "Graphics Designer",
    "Graphics Methods Specialist/Technologist",
    "Group Psychotherapy Psychologist",
    "Gynecologic Oncology Physician",
    "Gynecology Physician",
    "Hand Occupational Therapist",
    "Hand Physical Therapist",
    "Health & Wellness Coach",
    "Health Educator",
    "Health Information Specialist/Technologist",
    "Health Information Technician",
    "Health Maintenance Organization",
    "Health Psychologist",
    "Health Service Clinic/Center",
    "Health Service Psychologist",
    "Hearing  Aid Equipment",
    "Hearing Instrument Specialist",
    "Hearing and Speech Clinic/Center",
    "Hemapheresis Practitioner",
    "Hematology & Oncology Physician",
    "Hematology (Internal Medicine) Physician",
    "Hematology (Pathology) Physician",
    "Hematology Specialist/Technologist",
    "Hemodialysis Registered Nurse",
    "Hepatology Physician",
    "High-Risk Obstetric Registered Nurse",
    "Histology Specialist/Technologist",
    "Histology Technician",
    "Holistic Clinical Nurse Specialist",
    "Home Delivered Meals",
    "Home Health Agency",
    "Home Health Aide",
    "Home Health Certified Respiratory Therapist",
    "Home Health Clinical Nurse Specialist",
    "Home Health Registered Nurse",
    "Home Health Registered Respiratory Therapist",
    "Home Infusion Agency",
    "Home Infusion Therapy Pharmacy",
    "Home Modifications Contractor",
    "Homemaker",
    "Homeopath",
    "Hospice Registered Nurse",
    "Hospice and Palliative Medicine (Anesthesiology) Physician",
    "Hospice and Palliative Medicine (Emergency Medicine) Physician",
    "Hospice and Palliative Medicine (Family Medicine) Physician",
    "Hospice and Palliative Medicine (Internal Medicine) Physician",
    "Hospice and Palliative Medicine (Obstetrics & Gynecology) Physician",
    "Hospice and Palliative Medicine (Physical Medicine & Rehabilitation) Physician",
    "Hospice and Palliative Medicine (Psychiatry & Neurology) Physician",
    "Hospice and Palliative Medicine (Radiology) Physician",
    "Hospice and Palliative Medicine (Surgery) Physician",
    "Hospital Based Coding Specialist",
    "Hospitalist Physician",
    "Human Factors Occupational Therapist",
    "Human Factors Physical Therapist",
    "Hypertension Specialist Physician",
    "Immunology Pathology Specialist/Technologist",
    "Immunopathology Physician",
    "In Home Supportive Care Agency",
    "In Vivo & In Vitro Nuclear Medicine Physician",
    "Independent Duty Corpsman",
    "Independent Duty Medical Technicians",
    "Independent Medical Examiner Chiropractor",
    "Independent Medical Examiner Physician",
    "Indian Health Service/Tribal/Urban Indian Health (I/T/U) Pharmacy",
    "Infection Control Registered Nurse",
    "Infectious Disease Physician",
    "Infectious Diseases Pharmacist",
    "Informatics Clinical Nurse Specialist",
    "Infusion Therapy Clinic/Center",
    "Infusion Therapy Registered Nurse",
    "Inpatient Hospice",
    "Inpatient Obstetric Registered Nurse",
    "Institutional Pharmacy",
    "Integrative Medicine Physician",
    "Intellectual & Developmental Disabilities Psychologist",
    "Intellectual Disabilities Intermediate Care Facility",
    "Intellectual and/or Developmental Disabilities Community Based Residential Treatment Facility",
    "Intellectual and/or Developmental Disabilities Residential Treatment Facility",
    "Intermediate Emergency Medical Technician",
    "Internal Medicine Physician",
    "Internist Chiropractor",
    "Interpreter",
    "Interventional Cardiology Physician",
    "Interventional Pain Medicine Physician",
    "Kinesiotherapist",
    "Laboratory Management Specialist/Technologist",
    "Lactation Consultant (Non-RN)",
    "Lactation Consultant (Registered Nurse)",
    "Land Ambulance",
    "Lay Midwife",
    "Legal Medicine",
    "Legal Medicine (M.D./D.O.) Physician",
    "Licensed Practical Nurse",
    "Licensed Psychiatric Technician",
    "Licensed Vocational Nurse",
    "Lithotripsy Clinic/Center",
    "Local Education Agency (LEA)",
    "Lodging Provider",
    "Long Term Care Hospital",
    "Long Term Care Pharmacy",
    "Long-Term Care Clinical Nurse Specialist",
    "Low Vision Occupational Therapist",
    "Low Vision Occupational Therapy Assistant",
    "Low Vision Rehabilitation Optometrist",
    "Low-Risk Neonatal Registered Nurse",
    "MOHS-Micrographic Surgery Physician",
    "Magnetic Resonance Imaging (MRI) Clinic/Center",
    "Magnetic Resonance Imaging (MRI) Internal Medicine Physician",
    "Magnetic Resonance Imaging Radiologic Technologist",
    "Mail Order Pharmacy",
    "Mammography Clinic/Center",
    "Mammography Radiologic Technologist",
    "Managed Care Organization Pharmacy",
    "Marriage & Family Therapist",
    "Massage Therapist",
    "Mastectomy Fitter",
    "Maternal & Fetal Medicine Physician",
    "Maternal Newborn Registered Nurse",
    "Meals Provider",
    "Mechanotherapist",
    "Medical Art Specialist/Technologist",
    "Medical Biochemical Genetics",
    "Medical Foods Supplier",
    "Medical Geneticist (PhD) Specialist/Technologist",
    "Medical Illustrator",
    "Medical Laboratory Technician",
    "Medical Microbiology Physician",
    "Medical Oncology Physician",
    "Medical Physician Assistant",
    "Medical Research Veterinarian",
    "Medical Specialty Clinic/Center",
    "Medical Technologist",
    "Medical Toxicology (Emergency Medicine) Physician",
    "Medical Toxicology (Preventive Medicine) Physician",
    "Medical-Surgical Clinical Nurse Specialist",
    "Medical-Surgical Registered Nurse",
    "Medically Fragile Infants and Children Day Care",
    "Medicare Defined Swing Bed Hospital Unit",
    "Mental Health Clinic/Center (Including Community Mental Health Center)",
    "Mental Health Counselor",
    "Mental Health Occupational Therapist",
    "Mental Illness Community Based Residential Treatment Facility",
    "Mental Illness Intermediate Care Facility",
    "Metabolic Nutrition Registered Dietitian",
    "Methadone Clinic",
    "Microbiology Specialist/Technologist",
    "Midwife",
    "Migrant Health Clinic/Center",
    "Military Ambulatory Procedure Visits Operational (Transportable) Clinic/Center",
    "Military Clinical Medical Laboratory",
    "Military General Acute Care Hospital",
    "Military Health Care Provider",
    "Military Hospital",
    "Military Outpatient Operational (Transportable) Component Clinic/Center",
    "Military and U.S. Coast Guard Ambulatory Procedure Clinic/Center",
    "Military or U.S. Coast Guard Air Transport Ambulance",
    "Military or U.S. Coast Guard Ground Transport Ambulance",
    "Military or U.S. Coast Guard Water Transport Ambulance",
    "Military/U.S. Coast Guard Outpatient Clinic/Center",
    "Military/U.S. Coast Guard Pharmacy",
    "Military/U.S. Coast Guard Transport",
    "Mobile Mammography Clinic/Center",
    "Mobile Radiology Clinic/Center",
    "Molecular Genetic Pathology (Medical Genetics) Physician",
    "Molecular Genetic Pathology (Pathology) Physician",
    "Multi-Specialty Clinic/Center",
    "Multi-Specialty Group",
    "Music Therapist",
    "Naprapath",
    "Naturopath",
    "Neonatal Clinical Nurse Specialist",
    "Neonatal Intensive Care Registered Nurse",
    "Neonatal Nurse Practitioner",
    "Neonatal-Perinatal Medicine Physician",
    "Neonatal/Pediatric Certified Respiratory Therapist",
    "Neonatal/Pediatric Registered Respiratory Therapist",
    "Nephrology Physician",
    "Nephrology Registered Nurse",
    "Nephrology Specialist/Technologist",
    "Neuro-ophthalmology Physician",
    "Neurocritical Care Physician",
    "Neurodevelopmental Disabilities Physician",
    "Neurological Surgery Physician",
    "Neurology Chiropractor",
    "Neurology Physical Therapist",
    "Neurology Physician",
    "Neurology with Special Qualifications in Child Neurology Physician",
    "Neuromuscular Medicine (Physical Medicine & Rehabilitation) Physician",
    "Neuromuscular Medicine (Psychiatry & Neurology) Physician",
    "Neuromusculoskeletal Medicine & OMM Physician",
    "Neuropathology Physician",
    "Neuroradiology Physician",
    "Neurorehabilitation Occupational Therapist",
    "Neuroscience Clinical Nurse Specialist",
    "Neuroscience Registered Nurse",
    "Non-Pharmacy Dispensing Site",
    "Non-Surgical Family Planning Clinic/Center",
    "Non-emergency Medical Transport (VAN)",
    "Nuclear Cardiology Physician",
    "Nuclear Imaging & Therapy Physician",
    "Nuclear Medicine Physician",
    "Nuclear Medicine Technology Radiologic Technologist",
    "Nuclear Pharmacist",
    "Nuclear Pharmacy",
    "Nuclear Radiology Physician",
    "Nurse Massage Therapist (NMT)",
    "Nurse Practitioner",
    "Nurse's Aide",
    "Nursing Care Agency",
    "Nursing Facility Supplies (DME)",
    "Nursing Facility/Intermediate Care Facility",
    "Nursing Home Administrator",
    "Nutrition Chiropractor",
    "Nutrition Education Nutritionist",
    "Nutrition Support Pharmacist",
    "Nutrition Support Registered Nurse",
    "Nutritionist",
    "Obesity Medicine (Family Medicine) Physician",
    "Obesity Medicine (Internal Medicine) Physician",
    "Obesity Medicine (Obstetrics & Gynecology) Physician",
    "Obesity Medicine (Preventive Medicine) Physician",
    "Obesity Medicine (Psychiatry & Neurology) Physician",
    "Obesity and Weight Management Nutrition Registered Dietitian",
    "Obstetrics & Gynecology Nurse Practitioner",
    "Obstetrics & Gynecology Physician",
    "Obstetrics Physician",
    "Occupational Health Chiropractor",
    "Occupational Health Clinical Nurse Specialist",
    "Occupational Health Nurse Practitioner",
    "Occupational Health Registered Nurse",
    "Occupational Medicine Clinic/Center",
    "Occupational Medicine Physician",
    "Occupational Therapist",
    "Occupational Therapy Assistant",
    "Occupational Vision Optometrist",
    "Ocularist",
    "Oncology Clinic/Center",
    "Oncology Clinical Nurse Specialist",
    "Oncology Nutrition Registered Dietitian",
    "Oncology Pharmacist",
    "Oncology Registered Nurse",
    "Operational (Transportable) Military General Acute Care Hospital",
    "Ophthalmic Assistant",
    "Ophthalmic Plastic and Reconstructive Surgery Physician",
    "Ophthalmic Registered Nurse",
    "Ophthalmic Technician/Technologist",
    "Ophthalmologic Surgery Clinic/Center",
    "Ophthalmology Physician",
    "Optician",
    "Optometric Assistant Technician",
    "Optometric Technician",
    "Optometrist",
    "Oral & Maxillofacial Surgery (D.M.D.)",
    "Oral Medicine Dentistry",
    "Oral and Maxillofacial Pathology Dentistry",
    "Oral and Maxillofacial Radiology Dentistry",
    "Oral and Maxillofacial Surgery (Dentist)",
    "Oral and Maxillofacial Surgery Clinic/Center",
    "Organ Procurement Organization",
    "Orientation and Mobility Training Rehabilitation Counselor",
    "Orofacial Pain Dentistry",
    "Orthodontics and Dentofacial Orthopedics Dentistry",
    "Orthopaedic Foot and Ankle Surgery Physician",
    "Orthopaedic Hand Surgery Physician",
    "Orthopaedic Surgery Physician",
    "Orthopaedic Surgery of the Spine Physician",
    "Orthopaedic Trauma Physician",
    "Orthopedic Assistant",
    "Orthopedic Chiropractor",
    "Orthopedic Physical Therapist",
    "Orthopedic Registered Nurse",
    "Orthoptist",
    "Orthotic Fitter",
    "Orthotist",
    "Ostomy Care Registered Nurse",
    "Other Specialist/Technologist",
    "Other Technician",
    "Otolaryngic Allergy Physician",
    "Otolaryngology Physician",
    "Otolaryngology/Facial Plastic Surgery Physician",
    "Otology & Neurotology Physician",
    "Otorhinolaryngology & Head-Neck Registered Nurse",
    "Oxygen Equipment & Supplies (DME)",
    "PACE Provider Organization",
    "Pain Clinic/Center",
    "Pain Management Pharmacist",
    "Pain Management Registered Nurse",
    "Pain Medicine (Anesthesiology) Physician",
    "Pain Medicine (Physical Medicine & Rehabilitation) Physician",
    "Pain Medicine (Psychiatry & Neurology) Physician",
    "Pain Medicine Physician",
    "Palliative/Hospice Certified Respiratory Therapist",
    "Palliative/Hospice Registered Respiratory Therapist",
    "Paramedic",
    "Parenteral & Enteral Nutrition Supplies (DME)",
    "Pastoral Counselor",
    "Pathology Specialist/Technologist",
    "Pathology Technician",
    "Patient Transport Certified Respiratory Therapist",
    "Patient Transport Registered Respiratory Therapist",
    "Pediatric Adolescent Medicine Physician",
    "Pediatric Allergy/Immunology Physician",
    "Pediatric Anesthesiology Physician",
    "Pediatric Cardiology Physician",
    "Pediatric Chiropractor",
    "Pediatric Clinical & Laboratory Immunology Physician",
    "Pediatric Clinical Nurse Specialist",
    "Pediatric Critical Care Medicine Physician",
    "Pediatric Critical Care Nutrition Registered Dietitian",
    "Pediatric Dentistry",
    "Pediatric Dermatology Physician",
    "Pediatric Emergency Medicine (Emergency Medicine) Physician",
    "Pediatric Emergency Medicine (Pediatrics) Physician",
    "Pediatric Endocrinology Physician",
    "Pediatric Gastroenterology Physician",
    "Pediatric Hematology & Oncology Physician",
    "Pediatric Hospice and Palliative Medicine Physician",
    "Pediatric Infectious Diseases Physician",
    "Pediatric Medical Toxicology Physician",
    "Pediatric Nephrology Physician",
    "Pediatric Neurodevelopmental Disabilities Physician",
    "Pediatric Nurse Practitioner",
    "Pediatric Nutrition Registered Dietitian",
    "Pediatric Obesity Medicine Physician",
    "Pediatric Occupational Therapist",
    "Pediatric Oncology Clinical Nurse Specialist",
    "Pediatric Oncology Registered Nurse",
    "Pediatric Ophthalmology and Strabismus Specialist Physician",
    "Pediatric Optometrist",
    "Pediatric Orthopaedic Surgery Physician",
    "Pediatric Otolaryngology Physician",
    "Pediatric Pathology Physician",
    "Pediatric Pharmacist",
    "Pediatric Physical Therapist",
    "Pediatric Pulmonology Physician",
    "Pediatric Radiology Physician",
    "Pediatric Registered Nurse",
    "Pediatric Rehabilitation Medicine Physician",
    "Pediatric Rheumatology Physician",
    "Pediatric Skilled Nursing Facility",
    "Pediatric Sleep Medicine Physician",
    "Pediatric Sports Medicine Physician",
    "Pediatric Surgery Physician",
    "Pediatric Transplant Hepatology Physician",
    "Pediatric Urology Physician",
    "Pediatrics Physician",
    "Pedorthist",
    "Peer Specialist",
    "Perfusionist",
    "Perinatal Clinical Nurse Specialist",
    "Perinatal Nurse Practitioner",
    "Perinatal Registered Nurse",
    "Periodontics",
    "Perioperative Clinical Nurse Specialist",
    "Peritoneal Dialysis Registered Nurse",
    "Personal Care Attendant",
    "Personal Emergency Response Attendant",
    "Ph.D. Medical Genetics",
    "Ph.D. Medical Genetics Physician",
    "Pharmacist",
    "Pharmacist Clinician (PhC)/ Clinical Pharmacy Specialist",
    "Pharmacotherapy Pharmacist",
    "Pharmacy",
    "Pharmacy Technician",
    "Phlebology Physician",
    "Phlebotomy Technician",
    "Physical Disabilities Residential Treatment Facility",
    "Physical Medicine & Rehabilitation Physician",
    "Physical Rehabilitation Occupational Therapist",
    "Physical Therapist",
    "Physical Therapy Assistant",
    "Physical Therapy Clinic/Center",
    "Physician Assistant",
    "Physician Nutrition Specialist (Anesthesiology)",
    "Physician Nutrition Specialist (Family Medicine)",
    "Physician Nutrition Specialist (Internal Medicine)",
    "Physician Nutrition Specialist (Pediatrics)",
    "Physician Nutrition Specialist (Surgery)",
    "Physician Office Based Coding Specialist",
    "Physiological Laboratory",
    "Plastic Surgery Physician",
    "Plastic Surgery Registered Nurse",
    "Plastic Surgery Within the Head and Neck (Plastic Surgery) Physician",
    "Plastic Surgery within the Head & Neck (Otolaryngology) Physician",
    "Plastic and Reconstructive Surgery Physician",
    "Podiatric Assistant",
    "Podiatric Clinic/Center",
    "Podiatrist",
    "Poetry Therapist",
    "Point of Service",
    "Portable X-ray and/or Other Portable Diagnostic Imaging Supplier",
    "Preferred Provider Organization",
    "Prescribing (Medical) Psychologist",
    "Prevention Professional",
    "Preventive Medicine/Occupational Environmental Medicine Physician",
    "Primary Care Clinic/Center",
    "Primary Care Nurse Practitioner",
    "Primary Podiatric Medicine Podiatrist",
    "Prison Health Clinic/Center",
    "Private Vehicle",
    "Procedural Dermatology Physician",
    "Professional Counselor",
    "Prosthetic/Orthotic Supplier",
    "Prosthetics Case Management",
    "Prosthetist",
    "Prosthodontics",
    "Psychiatric Hospital",
    "Psychiatric Hospital Unit",
    "Psychiatric Pharmacist",
    "Psychiatric Residential Treatment Facility",
    "Psychiatric/Mental Health Clinical Nurse Specialist",
    "Psychiatric/Mental Health Nurse Practitioner",
    "Psychiatric/Mental Health Registered Nurse",
    "Psychiatry Physician",
    "Psychoanalysis Psychologist",
    "Psychoanalyst",
    "Psychologist",
    "Psychosomatic Medicine Physician",
    "Public Health & General Preventive Medicine Physician",
    "Public Health Dentistry",
    "Public Health or Welfare Agency",
    "Public Medicine Podiatrist",
    "Pulmonary Diagnostics Certified Respiratory Therapist",
    "Pulmonary Diagnostics Registered Respiratory Therapist",
    "Pulmonary Disease Physician",
    "Pulmonary Function Technologist",
    "Pulmonary Function Technologist Certified Respiratory Therapist",
    "Pulmonary Function Technologist Registered Respiratory Therapist",
    "Pulmonary Rehabilitation Certified Respiratory Therapist",
    "Pulmonary Rehabilitation Registered Respiratory Therapist",
    "Quality Management Radiologic Technologist",
    "Radiation Oncology Clinic/Center",
    "Radiation Oncology Physician",
    "Radiation Therapy Radiologic Technologist",
    "Radiography Radiologic Technologist",
    "Radiologic Technologist",
    "Radiological Physics Physician",
    "Radiology Chiropractor",
    "Radiology Clinic/Center",
    "Radiology Podiatrist",
    "Radiology Practitioner Assistant",
    "Recovery Care Clinic/Center",
    "Recreation Therapist",
    "Recreational Therapist Assistant",
    "Reflexologist",
    "Registered Dietetic Technician",
    "Registered Dietitian",
    "Registered Nurse",
    "Registered Nurse First Assistant",
    "Registered Record Administrator",
    "Registered Respiratory Therapist",
    "Rehabilitation Chiropractor",
    "Rehabilitation Clinic/Center",
    "Rehabilitation Clinical Nurse Specialist",
    "Rehabilitation Counselor",
    "Rehabilitation Hospital",
    "Rehabilitation Hospital Unit",
    "Rehabilitation Practitioner",
    "Rehabilitation Psychologist",
    "Rehabilitation Registered Nurse",
    "Religious Nonmedical Health Care Institution",
    "Religious Nonmedical Nursing Personnel",
    "Religious Nonmedical Practitioner",
    "Renal Dialysis Technician",
    "Renal Nutrition Registered Dietitian",
    "Reproductive Endocrinology Physician",
    "Reproductive Endocrinology/Infertility Registered Nurse",
    "Research Clinic/Center",
    "Research Study Abstracter/Coder",
    "Research Study Specialist",
    "Respiratory/Developmental/Rehabilitative Specialist/Technologist",
    "Respite Care",
    "Respite Care Camp",
    "Retina Specialist (Ophthalmology) Physician",
    "Rheumatology Physician",
    "Rural Acute Care Hospital",
    "Rural Health Clinic/Center",
    "SNF/Subacute Care Certified Respiratory Therapist",
    "SNF/Subacute Care Registered Respiratory Therapist",
    "School Clinical Nurse Specialist",
    "School Counselor",
    "School Nurse Practitioner",
    "School Psychologist",
    "School Registered Nurse",
    "School Social Worker",
    "Secured Medical Transport (VAN)",
    "Single Specialty Group",
    "Skilled Nursing Facility",
    "Sleep Disorder Diagnostic Clinic/Center",
    "Sleep Medicine (Family Medicine) Physician",
    "Sleep Medicine (Internal Medicine) Physician",
    "Sleep Medicine (Otolaryngology) Physician",
    "Sleep Medicine (Psychiatry & Neurology) Physician",
    "Sleep Specialist (PhD)",
    "Social Worker",
    "Solid Organ Transplant Pharmacist",
    "Sonography Radiologic Technologist",
    "Sonography Specialist/Technologist Cardiovascular",
    "Special Hospital",
    "Specialist",
    "Specialty Pharmacy",
    "Speech-Language Assistant",
    "Speech-Language Pathologist",
    "Speech/Language/Hearing Specialist/Technologist",
    "Spinal Cord Injury Medicine Physician",
    "Sports Dietetics Nutrition Registered Dietitian",
    "Sports Medicine (Emergency Medicine) Physician",
    "Sports Medicine (Family Medicine) Physician",
    "Sports Medicine (Internal Medicine) Physician",
    "Sports Medicine (Neuromusculoskeletal Medicine) Physician",
    "Sports Medicine (Orthopaedic Surgery) Physician",
    "Sports Medicine (Physical Medicine & Rehabilitation) Physician",
    "Sports Medicine (Preventive Medicine) Physician",
    "Sports Medicine (Psychiatry & Neurology) Physician",
    "Sports Medicine Podiatrist",
    "Sports Physical Therapist",
    "Sports Physician Chiropractor",
    "Sports Vision Optometrist",
    "State or Local Public Health Clinic/Center",
    "Student Health Clinic/Center",
    "Student in an Organized Health Care Education/Training Program",
    "Substance Abuse Rehabilitation Facility",
    "Substance Use Disorder Rehabilitation Clinic/Center",
    "Substance Use Disorder Rehabilitation Hospital Unit",
    "Supports Brokerage Agency",
    "Surgery Physician",
    "Surgery of the Hand (Plastic Surgery) Physician",
    "Surgery of the Hand (Surgery) Physician",
    "Surgical Assistant",
    "Surgical Critical Care Physician",
    "Surgical Oncology Physician",
    "Surgical Physician Assistant",
    "Surgical Technologist",
    "Taxi",
    "Technician",
    "Technician/Technologist",
    "Therapeutic Radiology Physician",
    "Thermography Chiropractor",
    "Thoracic Surgery (Cardiothoracic Vascular Surgery) Physician",
    "Train",
    "Transplant Hepatology Physician",
    "Transplant Surgery Physician",
    "Transplantation Clinical Nurse Specialist",
    "Transportation Broker",
    "Transportation Network Company",
    "Trauma Surgery Physician",
    "Undersea and Hyperbaric Medicine (Emergency Medicine) Physician",
    "Undersea and Hyperbaric Medicine (Preventive Medicine) Physician",
    "Urgent Care Clinic/Center",
    "Urogynecology and Reconstructive Pelvic Surgery (Obstetrics & Gynecology) Physician",
    "Urogynecology and Reconstructive Pelvic Surgery (Urology) Physician",
    "Urology Physician",
    "Urology Registered Nurse",
    "Uveitis and Ocular Inflammatory Disease (Ophthalmology) Physician",
    "VA Clinic/Center",
    "Vascular & Interventional Radiology Physician",
    "Vascular Neurology Physician",
    "Vascular Sonography Radiologic Technologist",
    "Vascular Specialist/Technologist Cardiovascular",
    "Vascular Surgery Physician",
    "Vascular-Interventional Technology Radiologic Technologist",
    "Vehicle Modifications Contractor",
    "Veterinarian",
    "Veterinary Technician",
    "Vision Therapy Optometrist",
    "Voluntary or Charitable Agency",
    "Water Ambulance",
    "Women's Health Clinical Nurse Specialist",
    "Women's Health Nurse Practitioner",
    "Women's Hospital",
    "Wound Care Registered Nurse",
]
