"""Share-token domain model — Phase 9.B.

A ``ShareToken`` allows an external recipient (not a docstats user) to view
a referral's clinical details via a 2FA-gated URL that expires.

Design decisions
----------------
- Token plaintext is URL-safe and generated by ``secrets.token_urlsafe(32)``.
  Only a SHA-256 hash is persisted — possessing the hash is not sufficient
  to construct a valid URL.
- ``second_factor_kind`` controls what the recipient must prove to unlock
  the viewer: ``patient_dob`` (ISO date), ``patient_phone_last4`` (4 digits),
  or ``none`` (admin-only deliveries with no external viewer, e.g. staff copy).
- ``second_factor_hash`` is ``HMAC-SHA256(SHARE_TOKEN_SECRET, answer)``
  so the cleartext answer never lands in the DB.
- Revocation is soft (``revoked_at`` timestamp).  Cancelling the parent
  delivery cascades to the token row (ON DELETE CASCADE).
- After ``MAX_FAILED_ATTEMPTS`` consecutive wrong 2FA answers the token is
  auto-revoked (brute-force guard).
"""

from __future__ import annotations

import hashlib
import hmac
import os
import secrets
from datetime import datetime, timedelta, timezone
from typing import Final

from pydantic import BaseModel

MAX_FAILED_ATTEMPTS: Final[int] = 5
DEFAULT_TOKEN_TTL_DAYS: Final[int] = 7


class ShareToken(BaseModel):
    id: int
    delivery_id: int
    token_hash: str
    expires_at: datetime
    revoked_at: datetime | None = None
    second_factor_kind: str = "none"  # patient_dob | patient_phone_last4 | none
    second_factor_hash: str | None = None
    view_count: int = 0
    failed_attempts: int = 0
    last_viewed_at: datetime | None = None
    created_at: datetime
    updated_at: datetime

    @property
    def is_valid(self) -> bool:
        """True when the token can still be used."""
        if self.revoked_at is not None:
            return False
        if datetime.now(tz=timezone.utc) >= self.expires_at:
            return False
        return True

    @property
    def requires_second_factor(self) -> bool:
        return self.second_factor_kind != "none"


def generate_token() -> str:
    """Return a URL-safe plaintext token (NOT stored in the DB)."""
    return secrets.token_urlsafe(32)


def hash_token(plaintext: str) -> str:
    """SHA-256 hex digest of the plaintext — stored in ``token_hash``."""
    return hashlib.sha256(plaintext.encode()).hexdigest()


def hash_second_factor(answer: str) -> str:
    """HMAC-SHA256(SHARE_TOKEN_SECRET, answer).  Raises ``ValueError`` when
    ``SHARE_TOKEN_SECRET`` is not configured."""
    secret = os.environ.get("SHARE_TOKEN_SECRET", "")
    if not secret:
        raise ValueError("SHARE_TOKEN_SECRET env var is not set")
    return hmac.new(secret.encode(), answer.strip().lower().encode(), hashlib.sha256).hexdigest()


def verify_second_factor(answer: str, stored_hash: str) -> bool:
    """Constant-time comparison of HMAC(answer) against ``stored_hash``."""
    try:
        computed = hash_second_factor(answer)
    except ValueError:
        return False
    return hmac.compare_digest(computed, stored_hash)


def token_expires_at(ttl_days: int = DEFAULT_TOKEN_TTL_DAYS) -> datetime:
    return datetime.now(tz=timezone.utc) + timedelta(days=ttl_days)
